test repo 1 pull 1
ADtestOrganization/test-repo-1 pull request #1
Opened 2023-12-05 12:48 UTC by kafelix496

2023-12-14 13:01 UTC, kafelix496 reviewed
test

2023-12-14 13:46 UTC, kafelix496 reviewed
is jisung's work done?

2023-12-14 13:46 UTC, kafelix496 reviewed
all review test

2023-12-14 14:16 UTC, jskurt reviewed
COMPLETE TEST ALL

2023-12-14 23:56 UTC, jskurt reviewed
RETEST

2023-12-15 07:25 UTC, jskurt reviewed
rebased onto main

2023-12-15 11:08 UTC, jskurt reviewed
TEST NIGHT

2023-12-15 11:08 UTC, jskurt reviewed
TEST NIGHT

2023-12-17 10:12 UTC, jskurt reviewed
test20231217

2023-12-17 10:23 UTC, jskurt approved these changes
tesetA

2023-12-22 03:59 UTC, jskurt reviewed
testToast

2023-12-22 04:00 UTC, jskurt reviewed
testToast2

2023-12-22 04:01 UTC, jskurt reviewed
testToast3

2023-12-22 04:02 UTC, jskurt approved these changes
testToast4

2023-12-22 04:02 UTC, jskurt requested changes
testToast5

2023-12-22 04:03 UTC, jskurt reviewed
testToast6

2023-12-22 04:03 UTC, jskurt reviewed
testToast7

2023-12-23 09:26 UTC, jskurt reviewed
test change folder

2023-12-24 13:29 UTC, jskurt approved these changes
pullTitle Test 1

2023-12-24 13:29 UTC, jskurt requested changes
pullTitle Test 2

2023-12-24 13:29 UTC, jskurt reviewed
pullTitle Test 2

2023-12-24 13:30 UTC, jskurt reviewed
pullTitle Test 3

2023-12-24 13:31 UTC, jskurt reviewed
pullTitle Test ALL

2023-12-25 14:04 UTC, jskurt reviewed
20231225_test

2023-12-25 14:05 UTC, jskurt requested changes
20231225_test2

2023-12-26 11:53 UTC, jskurt approved these changes
20231226_test2_3

2023-12-26 11:53 UTC, jskurt reviewed
20231226_test2_4

2023-12-27 05:37 UTC, jskurt reviewed
20231227_testAll

2024-01-01 11:44 UTC, jskurt reviewed
20240101_test1

2024-01-02 07:27 UTC, jskurt approved these changes
test approve

2024-01-03 10:59 UTC, jskurt approved these changes
20240103_test_done

2024-01-03 10:59 UTC, jskurt reviewed
20240103_test_done

2024-01-04 10:51 UTC, jskurt reviewed
20240104_test

2024-01-04 10:53 UTC, jskurt reviewed
20240104_comment-test

2024-01-04 10:53 UTC, jskurt approved these changes
20240104_approve-test

2024-01-04 10:54 UTC, jskurt requested changes
20240104_approve-test

2024-01-06 23:28 UTC, jskurt reviewed
20240107_test_complete

2024-01-06 23:31 UTC, jskurt approved these changes
20240104_test_complete

2024-01-09 03:02 UTC, jskurt reviewed
20240109-test-1

2024-01-09 03:32 UTC, jskurt reviewed
asdf

2024-01-09 03:42 UTC, jskurt reviewed
1234

2024-01-09 03:42 UTC, jskurt reviewed
123

2024-01-09 04:24 UTC, jskurt reviewed
adsfa

2024-01-09 04:40 UTC, jskurt reviewed
asdfd

2024-01-11 12:18 UTC, jskurt reviewed
test

2024-01-12 02:27 UTC, kafelix496 reviewed
abcd

2024-01-13 11:15 UTC, jskurt reviewed
a

2024-01-13 11:15 UTC, jskurt reviewed
d

2024-01-14 12:38 UTC, jskurt reviewed
111

2024-01-14 13:11 UTC, jskurt reviewed
test all pull list - 12

2024-01-15 00:57 UTC, kafelix496 reviewed
test

2024-01-15 00:59 UTC, kafelix496 reviewed
test

2024-01-15 01:01 UTC, kafelix496 reviewed
test

2024-01-15 01:03 UTC, jiyeol-lee reviewed
test

2024-01-15 01:04 UTC, kafelix496 reviewed
test

2024-01-15 01:04 UTC, kafelix496 reviewed
test

2024-01-15 01:05 UTC, kafelix496 reviewed
test

2024-01-16 01:42 UTC, jskurt reviewed
TEST

2024-01-16 08:28 UTC, jskurt reviewed
test all

2024-01-16 09:09 UTC, jskurt reviewed
TEST ALL

2024-01-16 09:12 UTC, jskurt reviewed
TEST ALL 20240116

2024-01-16 09:16 UTC, jskurt reviewed
TEST ALL 20240116_1

2024-01-16 09:18 UTC, jskurt reviewed
TEST ALL 20240116 2

2024-01-16 09:18 UTC, jskurt reviewed
TEST ALL 20240116 2

2024-01-16 09:18 UTC, jskurt approved these changes
TEST ALL 20240116 2

2024-01-16 09:20 UTC, jskurt approved these changes
TEST ALL 20240116 2

2024-01-16 09:36 UTC, jskurt reviewed
ALL TEST 20240116 1

2024-01-16 09:36 UTC, jskurt approved these changes
ALL TEST 20240116 1

2024-01-16 09:39 UTC, jskurt reviewed
TEST A

2024-01-16 09:43 UTC, jskurt reviewed
TEST 20240116 B

2024-01-16 09:43 UTC, jskurt approved these changes
TEST 20240116 B

2024-01-16 09:43 UTC, jskurt approved these changes
TEST 20240116 BB

2024-01-16 09:48 UTC, jisung-lee7 approved these changes
TEST 20240116 BB

2024-01-16 09:48 UTC, jskurt approved these changes
TEST 20240116 BB

2024-01-16 13:51 UTC, kafelix496 reviewed
test

2024-01-18 09:40 UTC, jskurt reviewed
testabc

2024-01-18 09:41 UTC, jskurt reviewed
testabcde

2024-01-18 09:42 UTC, jskurt reviewed
testabcdefg

2024-01-18 23:18 UTC, jskurt reviewed
test 20240119

2024-01-18 23:19 UTC, jskurt reviewed
test 20240119

2024-01-18 23:19 UTC, jskurt approved these changes
test 20240119

2024-01-20 14:08 UTC, jskurt reviewed
test 20240120

2024-01-20 14:08 UTC, jskurt approved these changes
test 20240120

2024-01-20 14:59 UTC, jskurt reviewed
test 20240120 test

2024-01-20 14:59 UTC, jskurt approved these changes
test 20240120 test

2024-01-20 15:00 UTC, jskurt reviewed
test 20240120 testaa

2024-01-21 06:29 UTC, jskurt reviewed
today test

2024-01-21 06:29 UTC, jskurt approved these changes
today test

2024-01-21 06:33 UTC, jskurt approved these changes
test translate

2024-01-21 06:33 UTC, jskurt approved these changes
test translate

2024-02-04 05:22 UTC, jskurt approved these changes
20240204 test in Vietnam

2024-02-12 03:11 UTC, jskurt reviewed
test

2024-02-12 03:36 UTC, kafelix496 reviewed
test

2024-02-23 02:26 UTC, jskurt reviewed
test20240223

2024-02-26 11:09 UTC, jskurt reviewed
test

2024-02-26 11:09 UTC, jskurt approved these changes
test1234

2024-02-28 07:08 UTC, jskurt approved these changes
20240228aa

2024-02-28 07:08 UTC, jskurt requested changes
20240228aa

2024-02-28 07:13 UTC, jskurt reviewed
test2024

2024-02-28 07:13 UTC, jskurt approved these changes
test2024

2024-02-28 07:14 UTC, jskurt requested changes
test2024

2024-02-28 07:14 UTC, jskurt approved these changes
test2024

2024-02-28 10:13 UTC, jskurt reviewed
testabc

2024-02-28 10:13 UTC, jskurt reviewed
testabcaa

2024-02-28 10:13 UTC, jisung-lee7 reviewed
testabcaa

2024-02-28 10:13 UTC, jskurt reviewed
testabcaa

2024-02-28 10:13 UTC, jskurt reviewed
testabcaa

2024-02-28 10:13 UTC, jskurt reviewed
testabcaa

2024-03-06 03:55 UTC, jskurt reviewed
test

2024-03-06 03:55 UTC, jskurt reviewed
testaa

2024-03-08 02:29 UTC, kafelix496 reviewed
test

2024-07-08 00:59 UTC, jisung-lee7 reviewed
test

2024-08-02 07:57 UTC, jisung-lee7 reviewed
12345

2024-08-23 15:23 UTC, jisung-lee7 reviewed
a

2024-11-06 23:33 UTC, jisung-lee7 reviewed
test

2024-11-10 19:33 UTC, jisung-lee7 reviewed
test

2024-11-14 07:30 UTC, jisung-lee7 reviewed
test

2024-11-14 07:31 UTC, jisung-lee7 reviewed
test2

2025-04-26 01:06 UTC, closed without merging